version: '3'

services:
  postgres:
    image: 'postgres:10'
    container_name: 'java-postgres'
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_URL: $POSTGRES_URL

  app:
    build: ./
    container_name: 'java-app'
    ports:
      - 8080:8080