spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/@database.name@?ApplicationName=base_task
    username: @database.username@
    password: @database.password@
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      dialect: org.hibernate.dialect.PostgreSQL10Dialect
  liquibase:
    change-log: classpath:liquibase/changelog.yml
springdoc :
  show-actuator: false
  swagger-ui:
    enabled: true
    path: /swagger-ui.html



